import { runner } from './src/runner';
import { SuiApplication, SuiDom, SmoScore, IsPitchLetter, SmoMusic, SmoMeasure, SmoNote, SmoOrnament, SmoInstrument, SmoSystemStaff, SmoSystemGroup, SmoSelector, SmoBeamer, createAndDisplayDialog, SuiNoteMenu, SmoOperation, SmoToXml, XmlToSmo, SuiXhrLoader, MidiToSmo, parseMidi } from 'smoosic';
/**
 * Expose the Smoosic symbols we need in the demo programs, and add them to our
 * default namespace
 */
export declare const Smo: {
    SuiApplication: typeof SuiApplication;
    SuiDom: typeof SuiDom;
    SmoScore: typeof SmoScore;
    IsPitchLetter: typeof IsPitchLetter;
    SmoMusic: typeof SmoMusic;
    SmoMeasure: typeof SmoMeasure;
    SmoNote: typeof SmoNote;
    SmoOrnament: typeof SmoOrnament;
    SmoInstrument: typeof SmoInstrument;
    SmoSystemStaff: typeof SmoSystemStaff;
    SmoSystemGroup: typeof SmoSystemGroup;
    SmoSelector: typeof SmoSelector;
    dynamicCtorInit: () => void;
    SmoBeamer: typeof SmoBeamer;
    createAndDisplayDialog: typeof createAndDisplayDialog;
    SuiNoteMenu: typeof SuiNoteMenu;
    SuiMenuCustomizer: (fcn: import("smoosic").customizeMenuOptionsFcn, ctor: string) => void;
    SmoOperation: typeof SmoOperation;
    SmoToXml: typeof SmoToXml;
    XmlToSmo: typeof XmlToSmo;
    SuiXhrLoader: typeof SuiXhrLoader;
    MidiToSmo: typeof MidiToSmo;
    parseMidi: typeof parseMidi;
    cardNotesLetterHtmlEn: {
        SmoConfiguration: typeof import("smoosic").SmoConfiguration;
        SuiApplication: typeof SuiApplication;
        dynamicCtorInit: () => void;
        parseMidi: typeof parseMidi;
        SuiDom: typeof SuiDom;
        SuiEventHandler: typeof import("smoosic").SuiEventHandler;
        SuiExceptionHandler: typeof import("smoosic").SuiExceptionHandler;
        Qwerty: typeof import("smoosic").Qwerty;
        SuiHelp: typeof import("smoosic").SuiHelp;
        SmoTranslationEditor: typeof import("smoosic").SmoTranslationEditor;
        ModalEventHandler: typeof import("smoosic").ModalEventHandler;
        simpleRibbonLayout: typeof import("smoosic").simpleRibbonLayout;
        RibbonButtons: typeof import("smoosic").RibbonButtons;
        DisplaySettings: typeof import("smoosic").DisplaySettings;
        ExtendedCollapseParent: typeof import("smoosic").ExtendedCollapseParent;
        CollapseRibbonControl: typeof import("smoosic").CollapseRibbonControl;
        SuiMenuManager: typeof import("smoosic").SuiMenuManager;
        SuiMenuBase: typeof import("smoosic").SuiMenuBase;
        SuiMenuCustomizer: (fcn: import("smoosic").customizeMenuOptionsFcn, ctor: string) => void;
        SuiScoreMenu: typeof import("smoosic").SuiScoreMenu;
        SuiFileMenu: typeof import("smoosic").SuiFileMenu;
        SuiDynamicsMenu: typeof import("smoosic").SuiDynamicsMenu;
        SuiTimeSignatureMenu: typeof import("smoosic").SuiTimeSignatureMenu;
        SuiKeySignatureMenu: typeof import("smoosic").SuiKeySignatureMenu;
        SuiStaffModifierMenu: typeof import("smoosic").SuiStaffModifierMenu;
        SuiLanguageMenu: typeof import("smoosic").SuiLanguageMenu;
        SuiMeasureMenu: typeof import("smoosic").SuiMeasureMenu;
        SuiNoteMenu: typeof SuiNoteMenu;
        SmoLanguage: typeof import("smoosic").SmoLanguage;
        SmoTranslator: typeof import("smoosic").SmoTranslator;
        SuiPartMenu: typeof import("smoosic").SuiPartMenu;
        SuiPartSelectionMenu: typeof import("smoosic").SuiPartSelectionMenu;
        SuiTextMenu: typeof import("smoosic").SuiTextMenu;
        SuiVoiceMenu: typeof import("smoosic").SuiVoiceMenu;
        SuiBeamMenu: typeof import("smoosic").SuiBeamMenu;
        SuiGraceNoteAdapter: typeof import("smoosic").SuiGraceNoteAdapter;
        SuiGraceNoteDialog: typeof import("smoosic").SuiGraceNoteDialog;
        SuiGraceNoteButtonsComponent: typeof import("smoosic").SuiGraceNoteButtonsComponent;
        SuiDurationAdapter: typeof import("smoosic").SuiDurationAdapter;
        SuiDurationDialog: typeof import("smoosic").SuiDurationDialog;
        SuiDurationButtonComponent: typeof import("smoosic").SuiDurationButtonComponent;
        SuiComponentAdapter: typeof import("smoosic").SuiComponentAdapter;
        SuiDialogAdapterBase: typeof import("smoosic").SuiDialogAdapterBase;
        SuiTempoDialog: typeof import("smoosic").SuiTempoDialog;
        SuiInstrumentDialog: typeof import("smoosic").SuiInstrumentDialog;
        SuiModifierDialogFactory: typeof import("smoosic").SuiModifierDialogFactory;
        SuiLibraryDialog: typeof import("smoosic").SuiLibraryDialog;
        SuiTextBracketDialog: typeof import("smoosic").SuiTextBracketDialog;
        SuiKeySignatureDialog: typeof import("smoosic").SuiKeySignatureDialog;
        SuiKeySignatureAdapter: typeof import("smoosic").SuiKeySignatureAdapter;
        SuiScoreViewDialog: typeof import("smoosic").SuiScoreViewDialog;
        SuiGlobalLayoutDialog: typeof import("smoosic").SuiGlobalLayoutDialog;
        SuiScoreIdentificationDialog: typeof import("smoosic").SuiScoreIdentificationDialog;
        SuiTransposeScoreAdapter: typeof import("smoosic").SuiTransposeScoreAdapter;
        SuiTransposeScoreDialog: typeof import("smoosic").SuiTransposeScoreDialog;
        SuiScoreFontDialog: typeof import("smoosic").SuiScoreFontDialog;
        SuiPageLayoutDialog: typeof import("smoosic").SuiPageLayoutDialog;
        SuiMeasureDialog: typeof import("smoosic").SuiMeasureDialog;
        SuiInsertMeasures: typeof import("smoosic").SuiInsertMeasures;
        SuiTimeSignatureDialog: typeof import("smoosic").SuiTimeSignatureDialog;
        SuiTextBlockDialog: typeof import("smoosic").SuiTextBlockDialog;
        SuiLyricDialog: typeof import("smoosic").SuiLyricDialog;
        SuiChordChangeDialog: typeof import("smoosic").SuiChordChangeDialog;
        SuiSlurAttributesDialog: typeof import("smoosic").SuiSlurAttributesDialog;
        SuiPedalMarkingDialog: typeof import("smoosic").SuiPedalMarkingDialog;
        SuiTieAttributesDialog: typeof import("smoosic").SuiTieAttributesDialog;
        SuiVoltaAttributeDialog: typeof import("smoosic").SuiVoltaAttributeDialog;
        SuiHairpinAttributesDialog: typeof import("smoosic").SuiHairpinAttributesDialog;
        SuiStaffGroupDialog: typeof import("smoosic").SuiStaffGroupDialog;
        helpModal: typeof import("smoosic").helpModal;
        SuiLoadFileDialog: typeof import("smoosic").SuiLoadFileDialog;
        SuiLoadMxmlDialog: typeof import("smoosic").SuiLoadMxmlDialog;
        SuiScorePreferencesDialog: typeof import("smoosic").SuiScorePreferencesDialog;
        SuiPartInfoDialog: typeof import("smoosic").SuiPartInfoDialog;
        SuiOrnamentDialog: typeof import("smoosic").SuiOrnamentDialog;
        SuiOrnamentButtonComponent: typeof import("smoosic").SuiOrnamentButtonComponent;
        SuiArticulationDialog: typeof import("smoosic").SuiArticulationDialog;
        SuiArticulationButtonComponent: typeof import("smoosic").SuiArticulationButtonComponent;
        SuiArticulationAdapter: typeof import("smoosic").SuiArticulationAdapter;
        SuiMicrotoneAdapter: typeof import("smoosic").SuiMicrotoneAdapter;
        SuiMicrotoneButtonComponent: typeof import("smoosic").SuiMicrotoneButtonComponent;
        SuiMicrotoneDialog: typeof import("smoosic").SuiMicrotoneDialog;
        SuiNoteHeadAdapter: typeof import("smoosic").SuiNoteHeadAdapter;
        SuiNoteHeadDialog: typeof import("smoosic").SuiNoteHeadDialog;
        SuiStemButtonComponent: typeof import("smoosic").SuiStemButtonComponent;
        SuiNoteHeadButtonComponent: typeof import("smoosic").SuiNoteHeadButtonComponent;
        SuiEndingsAdapter: typeof import("smoosic").SuiEndingsAdapter;
        SuiEndingsDialog: typeof import("smoosic").SuiEndingsDialog;
        SuiEndBarButtonComponent: typeof import("smoosic").SuiEndBarButtonComponent;
        SuiStartBarButtonComponent: typeof import("smoosic").SuiStartBarButtonComponent;
        SuiRepeatSymbolButtonComponent: typeof import("smoosic").SuiRepeatSymbolButtonComponent;
        SuiPrintFileDialog: typeof import("smoosic").SuiPrintFileDialog;
        SuiSaveFileDialog: typeof import("smoosic").SuiSaveFileDialog;
        SuiSaveXmlDialog: typeof import("smoosic").SuiSaveXmlDialog;
        SuiSaveVexDialog: typeof import("smoosic").SuiSaveVexDialog;
        SuiSaveMidiDialog: typeof import("smoosic").SuiSaveMidiDialog;
        SuiDialogBase: typeof import("smoosic").SuiDialogBase;
        createAndDisplayDialog: typeof createAndDisplayDialog;
        SuiPitchDialog: typeof import("smoosic").SuiPitchDialog;
        SuiPitchAdapter: typeof import("smoosic").SuiPitchAdapter;
        SuiIntervalButtonComponent: typeof import("smoosic").SuiIntervalButtonComponent;
        SuiLetterButtonComponent: typeof import("smoosic").SuiLetterButtonComponent;
        SuiTransposeButtonComponent: typeof import("smoosic").SuiTransposeButtonComponent;
        SuiTreeComponent: typeof import("smoosic").SuiTreeComponent;
        SuiDropdownComponent: typeof import("smoosic").SuiDropdownComponent;
        SuiRockerComponent: typeof import("smoosic").SuiRockerComponent;
        SuiFileDownloadComponent: typeof import("smoosic").SuiFileDownloadComponent;
        SuiButtonArrayComponent: typeof import("smoosic").SuiButtonArrayComponent;
        SuiButtonArrayMSComponent: typeof import("smoosic").SuiButtonArrayMSComponent;
        SuiToggleComponent: typeof import("smoosic").SuiToggleComponent;
        SuiButtonComponent: typeof import("smoosic").SuiButtonComponent;
        SuiDropdownComposite: typeof import("smoosic").SuiDropdownComposite;
        SuiToggleComposite: typeof import("smoosic").SuiToggleComposite;
        SuiButtonComposite: typeof import("smoosic").SuiButtonComposite;
        SuiRockerComposite: typeof import("smoosic").SuiRockerComposite;
        SuiTextInputComposite: typeof import("smoosic").SuiTextInputComposite;
        SuiFontComponent: typeof import("smoosic").SuiFontComponent;
        SuiTextInPlace: typeof import("smoosic").SuiTextInPlace;
        SuiLyricComponent: typeof import("smoosic").SuiLyricComponent;
        SuiChordComponent: typeof import("smoosic").SuiChordComponent;
        SuiDragText: typeof import("smoosic").SuiDragText;
        SuiNoteTextComponent: typeof import("smoosic").SuiNoteTextComponent;
        SuiTextBlockComponent: typeof import("smoosic").SuiTextBlockComponent;
        SuiTextInputComponent: typeof import("smoosic").SuiTextInputComponent;
        SuiReadOnlyTextComponent: typeof import("smoosic").SuiReadOnlyTextComponent;
        SuiDynamicModifierDialog: typeof import("smoosic").SuiDynamicModifierDialog;
        CheckboxDropdownComponent: typeof import("smoosic").CheckboxDropdownComponent;
        TieMappingComponent: typeof import("smoosic").TieMappingComponent;
        StaffAddRemoveComponent: typeof import("smoosic").StaffAddRemoveComponent;
        StaffCheckComponent: typeof import("smoosic").StaffCheckComponent;
        TextCheckComponent: typeof import("smoosic").TextCheckComponent;
        SuiArpeggioDialog: typeof import("smoosic").SuiArpeggioDialog;
        SuiClefChangeDialog: typeof import("smoosic").SuiClefChangeDialog;
        SuiPitchArrayComponent: typeof import("smoosic").SuiPitchArrayComponent;
        SuiPitchArrayComponentTab: typeof import("smoosic").SuiPitchArrayComponentTab;
        SuiPitchComponent: typeof import("smoosic").SuiPitchComponent;
        SuiPitchComposite: typeof import("smoosic").SuiPitchComposite;
        SuiXhrLoader: typeof SuiXhrLoader;
        PromiseHelpers: typeof import("smoosic").PromiseHelpers;
        SuiPiano: typeof import("smoosic").SuiPiano;
        layoutDebug: typeof import("smoosic").layoutDebug;
        SuiScoreView: typeof import("smoosic").SuiScoreView;
        SuiScroller: typeof import("smoosic").SuiScroller;
        SvgHelpers: typeof import("smoosic").SvgHelpers;
        SuiMapper: typeof import("smoosic").SuiMapper;
        SuiScoreRender: typeof import("smoosic").SuiScoreRender;
        SuiScoreViewOperations: typeof import("smoosic").SuiScoreViewOperations;
        TextFormatter: typeof import("smoosic").TextFormatter;
        VexFlow: typeof import("vexflow_smoosic/build/esm/types/src").Flow;
        SuiAudioPlayer: typeof import("smoosic").SuiAudioPlayer;
        SuiOscillator: typeof import("smoosic").SuiOscillator;
        SuiSampleMedia: typeof import("smoosic").SuiSampleMedia;
        SuiSampler: typeof import("smoosic").SuiSampler;
        SuiReverb: typeof import("smoosic").SuiReverb;
        SmoScore: typeof SmoScore;
        SmoScorePreferences: typeof import("smoosic").SmoScorePreferences;
        scoreModifierDynamicCtorInit: () => void;
        engravingFontTypes: import("smoosic").engravingFontType[];
        isEngravingFont: typeof import("smoosic").isEngravingFont;
        XmlToSmo: typeof XmlToSmo;
        SmoToXml: typeof SmoToXml;
        MidiToSmo: typeof MidiToSmo;
        SmoToMidi: typeof import("smoosic").SmoToMidi;
        SmoMusic: typeof SmoMusic;
        SmoAudioPitch: typeof import("smoosic").SmoAudioPitch;
        SmoMeasure: typeof SmoMeasure;
        SmoNamespace: {
            value: string;
        };
        SmoDynamicCtor: Record<string, import("smoosic").dynamicCtor>;
        SmoSystemStaff: typeof SmoSystemStaff;
        SmoNote: typeof SmoNote;
        IsPitchLetter: typeof IsPitchLetter;
        SmoStaffHairpin: typeof import("smoosic").SmoStaffHairpin;
        StaffModifierBase: typeof import("smoosic").StaffModifierBase;
        SmoStaffTextBracket: typeof import("smoosic").SmoStaffTextBracket;
        staffModifierDynamicCtorInit: () => void;
        SmoInstrument: typeof SmoInstrument;
        SmoSlur: typeof import("smoosic").SmoSlur;
        SmoPedalMarking: typeof import("smoosic").SmoPedalMarking;
        SmoTie: typeof import("smoosic").SmoTie;
        SmoTabStave: typeof import("smoosic").SmoTabStave;
        SmoSystemGroup: typeof SmoSystemGroup;
        SmoAudioPlayerSettings: typeof import("smoosic").SmoAudioPlayerSettings;
        SmoTextGroup: typeof import("smoosic").SmoTextGroup;
        SmoRehearsalMark: typeof import("smoosic").SmoRehearsalMark;
        SmoMeasureFormat: typeof import("smoosic").SmoMeasureFormat;
        SmoBarline: typeof import("smoosic").SmoBarline;
        SmoRepeatSymbol: typeof import("smoosic").SmoRepeatSymbol;
        SmoVolta: typeof import("smoosic").SmoVolta;
        SmoMeasureText: typeof import("smoosic").SmoMeasureText;
        SmoTempoText: typeof import("smoosic").SmoTempoText;
        TimeSignature: typeof import("smoosic").TimeSignature;
        measureModifierDynamicCtorInit: () => void;
        SmoOrnament: typeof SmoOrnament;
        noteModifierDynamicCtorInit: () => void;
        SmoArticulation: typeof import("smoosic").SmoArticulation;
        SmoDynamicText: typeof import("smoosic").SmoDynamicText;
        SmoGraceNote: typeof import("smoosic").SmoGraceNote;
        SmoMicrotone: typeof import("smoosic").SmoMicrotone;
        SmoLyric: typeof import("smoosic").SmoLyric;
        SmoArpeggio: typeof import("smoosic").SmoArpeggio;
        SmoClefChange: typeof import("smoosic").SmoClefChange;
        SmoSelection: typeof import("smoosic").SmoSelection;
        SmoSelector: typeof SmoSelector;
        UndoBuffer: typeof import("smoosic").UndoBuffer;
        SmoToVex: typeof import("smoosic").SmoToVex;
        SmoOperation: typeof SmoOperation;
        SmoBeamer: typeof SmoBeamer;
        cardKeysHtmlEn: string;
        cardNotesLetterHtmlEn: string;
        cardNotesChromaticHtmlEn: string;
        cardNotesChordsHtmlEn: string;
        cardNotesRestsHtmlEn: string;
        cardDurationNotesHtmlEn: string;
        cardDurationTupletsHtmlEn: string;
        cardSelectionsNotesHtmlEn: string;
        cardSelectionsModifiersHtmlEn: string;
        cardSelectionsNonSelectableHtmlEn: string;
        cardSelectionsSlashHtmlEn: string;
        cardBeamsAndStemsDirectionHtmlEn: string;
        cardBeamsAndStemsGroupingHtmlEn: string;
        cardMeasuresAddDeleteHtmlEn: string;
        cardVoicesCreateDeleteHtmlEn: string;
        cardPartAddDeleteHtmlEn: string;
        getClass: (jsonString: string) => any;
        buildDom: typeof import("smoosic").buildDom;
        addFileLink: typeof import("smoosic").addFileLink;
        InputTrapper: typeof import("smoosic").InputTrapper;
        draggable: typeof import("smoosic").draggable;
        closeDialogPromise: typeof import("smoosic").closeDialogPromise;
        getDomContainer: typeof import("smoosic").getDomContainer;
        createTopDomContainer: typeof import("smoosic").createTopDomContainer;
        renderVexTests: typeof import("smoosic").renderVexTests;
    };
};
export declare const demo: {
    runner: typeof runner;
    Smo: {
        SuiApplication: typeof SuiApplication;
        SuiDom: typeof SuiDom;
        SmoScore: typeof SmoScore;
        IsPitchLetter: typeof IsPitchLetter;
        SmoMusic: typeof SmoMusic;
        SmoMeasure: typeof SmoMeasure;
        SmoNote: typeof SmoNote;
        SmoOrnament: typeof SmoOrnament;
        SmoInstrument: typeof SmoInstrument;
        SmoSystemStaff: typeof SmoSystemStaff;
        SmoSystemGroup: typeof SmoSystemGroup;
        SmoSelector: typeof SmoSelector;
        dynamicCtorInit: () => void;
        SmoBeamer: typeof SmoBeamer;
        createAndDisplayDialog: typeof createAndDisplayDialog;
        SuiNoteMenu: typeof SuiNoteMenu;
        SuiMenuCustomizer: (fcn: import("smoosic").customizeMenuOptionsFcn, ctor: string) => void;
        SmoOperation: typeof SmoOperation;
        SmoToXml: typeof SmoToXml;
        XmlToSmo: typeof XmlToSmo;
        SuiXhrLoader: typeof SuiXhrLoader;
        MidiToSmo: typeof MidiToSmo;
        parseMidi: typeof parseMidi;
        cardNotesLetterHtmlEn: {
            SmoConfiguration: typeof import("smoosic").SmoConfiguration;
            SuiApplication: typeof SuiApplication;
            dynamicCtorInit: () => void;
            parseMidi: typeof parseMidi;
            SuiDom: typeof SuiDom;
            SuiEventHandler: typeof import("smoosic").SuiEventHandler;
            SuiExceptionHandler: typeof import("smoosic").SuiExceptionHandler;
            Qwerty: typeof import("smoosic").Qwerty;
            SuiHelp: typeof import("smoosic").SuiHelp;
            SmoTranslationEditor: typeof import("smoosic").SmoTranslationEditor;
            ModalEventHandler: typeof import("smoosic").ModalEventHandler;
            simpleRibbonLayout: typeof import("smoosic").simpleRibbonLayout;
            RibbonButtons: typeof import("smoosic").RibbonButtons;
            DisplaySettings: typeof import("smoosic").DisplaySettings;
            ExtendedCollapseParent: typeof import("smoosic").ExtendedCollapseParent;
            CollapseRibbonControl: typeof import("smoosic").CollapseRibbonControl;
            SuiMenuManager: typeof import("smoosic").SuiMenuManager;
            SuiMenuBase: typeof import("smoosic").SuiMenuBase;
            SuiMenuCustomizer: (fcn: import("smoosic").customizeMenuOptionsFcn, ctor: string) => void;
            SuiScoreMenu: typeof import("smoosic").SuiScoreMenu;
            SuiFileMenu: typeof import("smoosic").SuiFileMenu;
            SuiDynamicsMenu: typeof import("smoosic").SuiDynamicsMenu;
            SuiTimeSignatureMenu: typeof import("smoosic").SuiTimeSignatureMenu;
            SuiKeySignatureMenu: typeof import("smoosic").SuiKeySignatureMenu;
            SuiStaffModifierMenu: typeof import("smoosic").SuiStaffModifierMenu;
            SuiLanguageMenu: typeof import("smoosic").SuiLanguageMenu;
            SuiMeasureMenu: typeof import("smoosic").SuiMeasureMenu;
            SuiNoteMenu: typeof SuiNoteMenu;
            SmoLanguage: typeof import("smoosic").SmoLanguage;
            SmoTranslator: typeof import("smoosic").SmoTranslator;
            SuiPartMenu: typeof import("smoosic").SuiPartMenu;
            SuiPartSelectionMenu: typeof import("smoosic").SuiPartSelectionMenu;
            SuiTextMenu: typeof import("smoosic").SuiTextMenu;
            SuiVoiceMenu: typeof import("smoosic").SuiVoiceMenu;
            SuiBeamMenu: typeof import("smoosic").SuiBeamMenu;
            SuiGraceNoteAdapter: typeof import("smoosic").SuiGraceNoteAdapter;
            SuiGraceNoteDialog: typeof import("smoosic").SuiGraceNoteDialog;
            SuiGraceNoteButtonsComponent: typeof import("smoosic").SuiGraceNoteButtonsComponent;
            SuiDurationAdapter: typeof import("smoosic").SuiDurationAdapter;
            SuiDurationDialog: typeof import("smoosic").SuiDurationDialog;
            SuiDurationButtonComponent: typeof import("smoosic").SuiDurationButtonComponent;
            SuiComponentAdapter: typeof import("smoosic").SuiComponentAdapter;
            SuiDialogAdapterBase: typeof import("smoosic").SuiDialogAdapterBase;
            SuiTempoDialog: typeof import("smoosic").SuiTempoDialog;
            SuiInstrumentDialog: typeof import("smoosic").SuiInstrumentDialog;
            SuiModifierDialogFactory: typeof import("smoosic").SuiModifierDialogFactory;
            SuiLibraryDialog: typeof import("smoosic").SuiLibraryDialog;
            SuiTextBracketDialog: typeof import("smoosic").SuiTextBracketDialog;
            SuiKeySignatureDialog: typeof import("smoosic").SuiKeySignatureDialog;
            SuiKeySignatureAdapter: typeof import("smoosic").SuiKeySignatureAdapter;
            SuiScoreViewDialog: typeof import("smoosic").SuiScoreViewDialog;
            SuiGlobalLayoutDialog: typeof import("smoosic").SuiGlobalLayoutDialog;
            SuiScoreIdentificationDialog: typeof import("smoosic").SuiScoreIdentificationDialog;
            SuiTransposeScoreAdapter: typeof import("smoosic").SuiTransposeScoreAdapter;
            SuiTransposeScoreDialog: typeof import("smoosic").SuiTransposeScoreDialog;
            SuiScoreFontDialog: typeof import("smoosic").SuiScoreFontDialog;
            SuiPageLayoutDialog: typeof import("smoosic").SuiPageLayoutDialog;
            SuiMeasureDialog: typeof import("smoosic").SuiMeasureDialog;
            SuiInsertMeasures: typeof import("smoosic").SuiInsertMeasures;
            SuiTimeSignatureDialog: typeof import("smoosic").SuiTimeSignatureDialog;
            SuiTextBlockDialog: typeof import("smoosic").SuiTextBlockDialog;
            SuiLyricDialog: typeof import("smoosic").SuiLyricDialog;
            SuiChordChangeDialog: typeof import("smoosic").SuiChordChangeDialog;
            SuiSlurAttributesDialog: typeof import("smoosic").SuiSlurAttributesDialog;
            SuiPedalMarkingDialog: typeof import("smoosic").SuiPedalMarkingDialog;
            SuiTieAttributesDialog: typeof import("smoosic").SuiTieAttributesDialog;
            SuiVoltaAttributeDialog: typeof import("smoosic").SuiVoltaAttributeDialog;
            SuiHairpinAttributesDialog: typeof import("smoosic").SuiHairpinAttributesDialog;
            SuiStaffGroupDialog: typeof import("smoosic").SuiStaffGroupDialog;
            helpModal: typeof import("smoosic").helpModal;
            SuiLoadFileDialog: typeof import("smoosic").SuiLoadFileDialog;
            SuiLoadMxmlDialog: typeof import("smoosic").SuiLoadMxmlDialog;
            SuiScorePreferencesDialog: typeof import("smoosic").SuiScorePreferencesDialog;
            SuiPartInfoDialog: typeof import("smoosic").SuiPartInfoDialog;
            SuiOrnamentDialog: typeof import("smoosic").SuiOrnamentDialog;
            SuiOrnamentButtonComponent: typeof import("smoosic").SuiOrnamentButtonComponent;
            SuiArticulationDialog: typeof import("smoosic").SuiArticulationDialog;
            SuiArticulationButtonComponent: typeof import("smoosic").SuiArticulationButtonComponent;
            SuiArticulationAdapter: typeof import("smoosic").SuiArticulationAdapter;
            SuiMicrotoneAdapter: typeof import("smoosic").SuiMicrotoneAdapter;
            SuiMicrotoneButtonComponent: typeof import("smoosic").SuiMicrotoneButtonComponent;
            SuiMicrotoneDialog: typeof import("smoosic").SuiMicrotoneDialog;
            SuiNoteHeadAdapter: typeof import("smoosic").SuiNoteHeadAdapter;
            SuiNoteHeadDialog: typeof import("smoosic").SuiNoteHeadDialog;
            SuiStemButtonComponent: typeof import("smoosic").SuiStemButtonComponent;
            SuiNoteHeadButtonComponent: typeof import("smoosic").SuiNoteHeadButtonComponent;
            SuiEndingsAdapter: typeof import("smoosic").SuiEndingsAdapter;
            SuiEndingsDialog: typeof import("smoosic").SuiEndingsDialog;
            SuiEndBarButtonComponent: typeof import("smoosic").SuiEndBarButtonComponent;
            SuiStartBarButtonComponent: typeof import("smoosic").SuiStartBarButtonComponent;
            SuiRepeatSymbolButtonComponent: typeof import("smoosic").SuiRepeatSymbolButtonComponent;
            SuiPrintFileDialog: typeof import("smoosic").SuiPrintFileDialog;
            SuiSaveFileDialog: typeof import("smoosic").SuiSaveFileDialog;
            SuiSaveXmlDialog: typeof import("smoosic").SuiSaveXmlDialog;
            SuiSaveVexDialog: typeof import("smoosic").SuiSaveVexDialog;
            SuiSaveMidiDialog: typeof import("smoosic").SuiSaveMidiDialog;
            SuiDialogBase: typeof import("smoosic").SuiDialogBase;
            createAndDisplayDialog: typeof createAndDisplayDialog;
            SuiPitchDialog: typeof import("smoosic").SuiPitchDialog;
            SuiPitchAdapter: typeof import("smoosic").SuiPitchAdapter;
            SuiIntervalButtonComponent: typeof import("smoosic").SuiIntervalButtonComponent;
            SuiLetterButtonComponent: typeof import("smoosic").SuiLetterButtonComponent;
            SuiTransposeButtonComponent: typeof import("smoosic").SuiTransposeButtonComponent;
            SuiTreeComponent: typeof import("smoosic").SuiTreeComponent;
            SuiDropdownComponent: typeof import("smoosic").SuiDropdownComponent;
            SuiRockerComponent: typeof import("smoosic").SuiRockerComponent;
            SuiFileDownloadComponent: typeof import("smoosic").SuiFileDownloadComponent;
            SuiButtonArrayComponent: typeof import("smoosic").SuiButtonArrayComponent;
            SuiButtonArrayMSComponent: typeof import("smoosic").SuiButtonArrayMSComponent;
            SuiToggleComponent: typeof import("smoosic").SuiToggleComponent;
            SuiButtonComponent: typeof import("smoosic").SuiButtonComponent;
            SuiDropdownComposite: typeof import("smoosic").SuiDropdownComposite;
            SuiToggleComposite: typeof import("smoosic").SuiToggleComposite;
            SuiButtonComposite: typeof import("smoosic").SuiButtonComposite;
            SuiRockerComposite: typeof import("smoosic").SuiRockerComposite;
            SuiTextInputComposite: typeof import("smoosic").SuiTextInputComposite;
            SuiFontComponent: typeof import("smoosic").SuiFontComponent;
            SuiTextInPlace: typeof import("smoosic").SuiTextInPlace;
            SuiLyricComponent: typeof import("smoosic").SuiLyricComponent;
            SuiChordComponent: typeof import("smoosic").SuiChordComponent;
            SuiDragText: typeof import("smoosic").SuiDragText;
            SuiNoteTextComponent: typeof import("smoosic").SuiNoteTextComponent;
            SuiTextBlockComponent: typeof import("smoosic").SuiTextBlockComponent;
            SuiTextInputComponent: typeof import("smoosic").SuiTextInputComponent;
            SuiReadOnlyTextComponent: typeof import("smoosic").SuiReadOnlyTextComponent;
            SuiDynamicModifierDialog: typeof import("smoosic").SuiDynamicModifierDialog;
            CheckboxDropdownComponent: typeof import("smoosic").CheckboxDropdownComponent;
            TieMappingComponent: typeof import("smoosic").TieMappingComponent;
            StaffAddRemoveComponent: typeof import("smoosic").StaffAddRemoveComponent;
            StaffCheckComponent: typeof import("smoosic").StaffCheckComponent;
            TextCheckComponent: typeof import("smoosic").TextCheckComponent;
            SuiArpeggioDialog: typeof import("smoosic").SuiArpeggioDialog;
            SuiClefChangeDialog: typeof import("smoosic").SuiClefChangeDialog;
            SuiPitchArrayComponent: typeof import("smoosic").SuiPitchArrayComponent;
            SuiPitchArrayComponentTab: typeof import("smoosic").SuiPitchArrayComponentTab;
            SuiPitchComponent: typeof import("smoosic").SuiPitchComponent;
            SuiPitchComposite: typeof import("smoosic").SuiPitchComposite;
            SuiXhrLoader: typeof SuiXhrLoader;
            PromiseHelpers: typeof import("smoosic").PromiseHelpers;
            SuiPiano: typeof import("smoosic").SuiPiano;
            layoutDebug: typeof import("smoosic").layoutDebug;
            SuiScoreView: typeof import("smoosic").SuiScoreView;
            SuiScroller: typeof import("smoosic").SuiScroller;
            SvgHelpers: typeof import("smoosic").SvgHelpers;
            SuiMapper: typeof import("smoosic").SuiMapper;
            SuiScoreRender: typeof import("smoosic").SuiScoreRender;
            SuiScoreViewOperations: typeof import("smoosic").SuiScoreViewOperations;
            TextFormatter: typeof import("smoosic").TextFormatter;
            VexFlow: typeof import("vexflow_smoosic/build/esm/types/src").Flow;
            SuiAudioPlayer: typeof import("smoosic").SuiAudioPlayer;
            SuiOscillator: typeof import("smoosic").SuiOscillator;
            SuiSampleMedia: typeof import("smoosic").SuiSampleMedia;
            SuiSampler: typeof import("smoosic").SuiSampler;
            SuiReverb: typeof import("smoosic").SuiReverb;
            SmoScore: typeof SmoScore;
            SmoScorePreferences: typeof import("smoosic").SmoScorePreferences;
            scoreModifierDynamicCtorInit: () => void;
            engravingFontTypes: import("smoosic").engravingFontType[];
            isEngravingFont: typeof import("smoosic").isEngravingFont;
            XmlToSmo: typeof XmlToSmo;
            SmoToXml: typeof SmoToXml;
            MidiToSmo: typeof MidiToSmo;
            SmoToMidi: typeof import("smoosic").SmoToMidi;
            SmoMusic: typeof SmoMusic;
            SmoAudioPitch: typeof import("smoosic").SmoAudioPitch;
            SmoMeasure: typeof SmoMeasure;
            SmoNamespace: {
                value: string;
            };
            SmoDynamicCtor: Record<string, import("smoosic").dynamicCtor>;
            SmoSystemStaff: typeof SmoSystemStaff;
            SmoNote: typeof SmoNote;
            IsPitchLetter: typeof IsPitchLetter;
            SmoStaffHairpin: typeof import("smoosic").SmoStaffHairpin;
            StaffModifierBase: typeof import("smoosic").StaffModifierBase;
            SmoStaffTextBracket: typeof import("smoosic").SmoStaffTextBracket;
            staffModifierDynamicCtorInit: () => void;
            SmoInstrument: typeof SmoInstrument;
            SmoSlur: typeof import("smoosic").SmoSlur;
            SmoPedalMarking: typeof import("smoosic").SmoPedalMarking;
            SmoTie: typeof import("smoosic").SmoTie;
            SmoTabStave: typeof import("smoosic").SmoTabStave;
            SmoSystemGroup: typeof SmoSystemGroup;
            SmoAudioPlayerSettings: typeof import("smoosic").SmoAudioPlayerSettings;
            SmoTextGroup: typeof import("smoosic").SmoTextGroup;
            SmoRehearsalMark: typeof import("smoosic").SmoRehearsalMark;
            SmoMeasureFormat: typeof import("smoosic").SmoMeasureFormat;
            SmoBarline: typeof import("smoosic").SmoBarline;
            SmoRepeatSymbol: typeof import("smoosic").SmoRepeatSymbol;
            SmoVolta: typeof import("smoosic").SmoVolta;
            SmoMeasureText: typeof import("smoosic").SmoMeasureText;
            SmoTempoText: typeof import("smoosic").SmoTempoText;
            TimeSignature: typeof import("smoosic").TimeSignature;
            measureModifierDynamicCtorInit: () => void;
            SmoOrnament: typeof SmoOrnament;
            noteModifierDynamicCtorInit: () => void;
            SmoArticulation: typeof import("smoosic").SmoArticulation;
            SmoDynamicText: typeof import("smoosic").SmoDynamicText;
            SmoGraceNote: typeof import("smoosic").SmoGraceNote;
            SmoMicrotone: typeof import("smoosic").SmoMicrotone;
            SmoLyric: typeof import("smoosic").SmoLyric;
            SmoArpeggio: typeof import("smoosic").SmoArpeggio;
            SmoClefChange: typeof import("smoosic").SmoClefChange;
            SmoSelection: typeof import("smoosic").SmoSelection;
            SmoSelector: typeof SmoSelector;
            UndoBuffer: typeof import("smoosic").UndoBuffer;
            SmoToVex: typeof import("smoosic").SmoToVex;
            SmoOperation: typeof SmoOperation;
            SmoBeamer: typeof SmoBeamer;
            cardKeysHtmlEn: string;
            cardNotesLetterHtmlEn: string;
            cardNotesChromaticHtmlEn: string;
            cardNotesChordsHtmlEn: string;
            cardNotesRestsHtmlEn: string;
            cardDurationNotesHtmlEn: string;
            cardDurationTupletsHtmlEn: string;
            cardSelectionsNotesHtmlEn: string;
            cardSelectionsModifiersHtmlEn: string;
            cardSelectionsNonSelectableHtmlEn: string;
            cardSelectionsSlashHtmlEn: string;
            cardBeamsAndStemsDirectionHtmlEn: string;
            cardBeamsAndStemsGroupingHtmlEn: string;
            cardMeasuresAddDeleteHtmlEn: string;
            cardVoicesCreateDeleteHtmlEn: string;
            cardPartAddDeleteHtmlEn: string;
            getClass: (jsonString: string) => any;
            buildDom: typeof import("smoosic").buildDom;
            addFileLink: typeof import("smoosic").addFileLink;
            InputTrapper: typeof import("smoosic").InputTrapper;
            draggable: typeof import("smoosic").draggable;
            closeDialogPromise: typeof import("smoosic").closeDialogPromise;
            getDomContainer: typeof import("smoosic").getDomContainer;
            createTopDomContainer: typeof import("smoosic").createTopDomContainer;
            renderVexTests: typeof import("smoosic").renderVexTests;
        };
    };
    QTest: QUnit.TestFunction;
    QModule: moduleFunction & moduleFunctionWithOptions & ModuleOnly & ModuleSkip & ModuleIf & ModuleTodo;
    QStart: () => void;
};
export default demo;
//# sourceMappingURL=index.d.ts.map